name: maven CI

on: [push]

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
      - name: upload artifactory
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: target/MockingExample-1.0-SNAPSHOT.jar